### ISSUE TITLE
扫描区块的交易，网络链接会越来越多，有泄露，如何处理呀

### ISSUE THREAD

**Issue by fcwrsmall** [ranjbar-dev/tron-wallet#4]

**Comment by fcwrsmall** [comment]
找到泄露的原因了，GetGrpcClient接口中每次都会err := c.Start(grpc.WithTransportCredentials(insecure.NewCredentials()))，只需要全局创建一个就可以了

**Comment by ranjbar-dev** [comment]
Hello,
Checkout this commit if it did not solve your problem create new issue 
https://github.com/ranjbar-dev/tron-wallet/commit/5a6596c8d6298e50e8bbae0ef7796c4087d8e7b2
Good Luck!
